/*
 * Copyright (C) 2026, Robert Patterson
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#include "musicxml.h"

#include <algorithm>
#include <array>
#include <optional>
#include <string_view>

#include "musx/dom/InstrumentUuids.h"
#include "mx/api/SoundID.h"

using namespace musx::dom;

namespace denigma {
namespace formats {
namespace musicxml {
namespace detail {

namespace {

using SoundID = mx::api::SoundID;

struct InstrumentSoundMapping
{
    std::string_view instUuid;
    SoundID soundId;
};

} // namespace

std::optional<mx::api::SoundID> musicXmlSoundIdFromInstrumentUuid(std::string_view instUuid)
{
    static constexpr auto table = std::to_array<InstrumentSoundMapping>({
        // { uuid::BlankStaff,                     SoundID:: },
        // { uuid::BlankStaff2,                    SoundID:: },
        // { uuid::GrandStaff,                     SoundID:: },
        // { uuid::Unknown,                        SoundID:: },
        // Strings
        { uuid::Violin,                         SoundID::stringsViolin },
        { uuid::Viola,                          SoundID::stringsViola },
        { uuid::Cello,                          SoundID::stringsCello },
        { uuid::DoubleBass,                     SoundID::stringsContrabass },
        { uuid::ViolinSection,                  SoundID::stringsViolin },
        { uuid::ViolaSection,                   SoundID::stringsViola },
        { uuid::CelloSection,                   SoundID::stringsCello },
        { uuid::VioloncelloSection,             SoundID::stringsCello },
        { uuid::DoubleBassSection,              SoundID::stringsContrabass },
        { uuid::ContrabassSection,              SoundID::stringsContrabass },
        { uuid::StringEnsemble,                 SoundID::stringsGroup },
        { uuid::ViolaDAmore,                    SoundID::stringsViolaDamore },
        { uuid::Ajaeng,                         SoundID::stringsAjaeng },
        { uuid::Arpeggione,                     SoundID::stringsArpeggione },
        { uuid::Baryton,                        SoundID::stringsBaryton },
        { uuid::ByzantineLyra,                  SoundID::stringsLyraByzantine },
        { uuid::CretanLyra,                     SoundID::stringsLyraCretan },
        { uuid::Crwth,                          SoundID::stringsCrwth },
        { uuid::Dahu,                           SoundID::stringsErhu },
        { uuid::Dangao,                         SoundID::stringsDanGao },
        { uuid::Dihu,                           SoundID::stringsDihu },
        { uuid::Erhu,                           SoundID::stringsErhu },
        { uuid::Erxian,                         SoundID::stringsErxian },
        { uuid::Fiddle,                         SoundID::stringsFiddle },
        { uuid::Gaohu,                          SoundID::stringsGaohu },
        { uuid::Gehu,                           SoundID::stringsGehu },
        { uuid::Haegeum,                        SoundID::stringsHaegeum },
        { uuid::HardangerFiddle,                SoundID::stringsFiddleHardanger },
        { uuid::HurdyGurdy,                     SoundID::stringsHurdyGurdy },
        { uuid::Igil,                           SoundID::stringsIgil },
        { uuid::Kamancha,                       SoundID::stringsKamancha },
        { uuid::Kokyu,                          SoundID::stringsKokyu },
        { uuid::Kora,                           SoundID::pluckKora },
        { uuid::LaruAn,                         SoundID::stringsLaruan },
        { uuid::Leiqin,                         SoundID::stringsLeiqin },
        { uuid::Lirone,                         SoundID::stringsLirone },
        { uuid::MorinKhuur,                     SoundID::stringsMorinKhuur },
        { uuid::Nyckelharpa,                    SoundID::stringsNyckelharpa },
        { uuid::Octobass,                       SoundID::stringsOctobass },
        { uuid::Rebab,                          SoundID::stringsRebab },
        { uuid::Rebec,                          SoundID::stringsRebec },
        { uuid::Sarangi,                        SoundID::stringsSarangi },
        { uuid::SarangiDrone,                   SoundID::stringsSarangi },
        { uuid::StrohViolin,                    SoundID::stringsStrohViolin },
        { uuid::Trombamarina,                   SoundID::stringsTrombaMarina },
        { uuid::Vielle,                         SoundID::stringsVielle },
        { uuid::Viol,                           SoundID::stringsViol },
        { uuid::ViolaDaGamba,                   SoundID::stringsViol },
        { uuid::ViolinoPiccolo,                 SoundID::stringsViolonoPiccolo },
        { uuid::VioloncelloPiccolo,             SoundID::stringsCelloPiccolo },
        { uuid::Violotta,                       SoundID::stringsViolotta },
        { uuid::Zhonghu,                        SoundID::stringsZhonghu },

        // Keyboards
        { uuid::Piano,                          SoundID::keyboardPiano },
        { uuid::PianoNoName,                    SoundID::keyboardPiano },
        { uuid::Harpsichord,                    SoundID::keyboardHarpsichord },
        { uuid::Organ,                          SoundID::keyboardOrgan },
        { uuid::Organ2Staff,                    SoundID::keyboardOrgan },
        { uuid::Celesta,                        SoundID::keyboardCelesta },
        { uuid::Accordion,                      SoundID::keyboardAccordion },
        { uuid::Melodica,                       SoundID::windReedMelodica },
        { uuid::ElectricPiano,                  SoundID::keyboardPianoElectric },
        { uuid::Clavinet,                       SoundID::keyboardClavichord },
        { uuid::SynthPad,                       SoundID::synthPad },
        { uuid::SynthLead,                      SoundID::synthToneSawtooth },
        { uuid::SynthBrass,                     SoundID::brassGroupSynth },
        { uuid::SynthSoundtrack,                SoundID::synthEffectsSoundtrack },
        { uuid::SoundFX,                        SoundID::synthEffects },
        { uuid::Harmonium,                      SoundID::keyboardHarmonium },
        { uuid::OndesMartenot,                  SoundID::keyboardOndesMartenot },
        { uuid::Theremin,                       SoundID::synthTheremin },
        { uuid::Virginal,                       SoundID::keyboardVirginal },
        { uuid::Clavichord,                     SoundID::keyboardClavichord },

        // Voices
        { uuid::SopranoVoice,                   SoundID::voiceSoprano },
        { uuid::AltoVoice,                      SoundID::voiceAlto },
        { uuid::TenorVoice,                     SoundID::voiceTenor },
        { uuid::BaritoneVoice,                  SoundID::voiceBaritone },
        { uuid::BassVoice,                      SoundID::voiceBass },
        { uuid::Vocals,                         SoundID::voiceVocals },
        { uuid::Voice,                          SoundID::voiceVocals },
        { uuid::VoiceNoName,                    SoundID::voiceVocals },
        { uuid::MezzoSopranoVoice,              SoundID::voiceMezzoSoprano },
        { uuid::ContraltoVoice,                 SoundID::voiceAlto },
        { uuid::CountertenorVoice,              SoundID::voiceCountertenor },
        { uuid::BassBaritoneVoice,              SoundID::voiceBass },
        { uuid::ChoirAahs,                      SoundID::voiceAa },
        { uuid::ChoirOohs,                      SoundID::voiceOo },
        { uuid::Yodel,                          SoundID::voiceVocals },
        { uuid::Beatbox,                        SoundID::voicePercussionBeatbox },
        { uuid::Kazoo,                          SoundID::voiceKazoo },
        { uuid::Talkbox,                        SoundID::voiceTalkBox },
        { uuid::VocalPercussion,                SoundID::voicePercussion },

        // Woodwinds
        { uuid::Piccolo,                        SoundID::windFlutesFlutePiccolo },
        { uuid::Flute,                          SoundID::windFlutesFlute },
        { uuid::AltoFlute,                      SoundID::windFlutesFluteAlto },
        { uuid::Oboe,                           SoundID::windReedOboe },
        { uuid::OboeDAmore,                     SoundID::windReedOboeDamore },
        { uuid::EnglishHorn,                    SoundID::windReedEnglishHorn },
        { uuid::ClarinetBFlat,                  SoundID::windReedClarinetBflat },
        { uuid::ClarinetA,                      SoundID::windReedClarinetA },
        { uuid::ClarinetEFlat,                  SoundID::windReedClarinetEflat },
        { uuid::AltoClarinet,                   SoundID::windReedClarinetAlto },
        { uuid::ContraltoClarinet,              SoundID::windReedClarinetContraAlto },
        { uuid::BassClarinet,                   SoundID::windReedClarinetBass },
        { uuid::ContrabassClarinet,             SoundID::windReedClarinetContrabass },
        { uuid::Bassoon,                        SoundID::windReedBassoon },
        { uuid::Contrabassoon,                  SoundID::windReedContrabassoon },
        { uuid::WindSection,                    SoundID::windGroup },
        { uuid::SopranoSax,                     SoundID::windReedSaxophoneSoprano },
        { uuid::AltoSax,                        SoundID::windReedSaxophoneAlto },
        { uuid::TenorSax,                       SoundID::windReedSaxophoneTenor },
        { uuid::BaritoneSax,                    SoundID::windReedSaxophoneBaritone },
        { uuid::SopranoRecorder,                SoundID::windFlutesRecorderSoprano },
        { uuid::SopraninoRecorder,              SoundID::windFlutesRecorderSopranino },
        { uuid::AltoRecorder,                   SoundID::windFlutesRecorderAlto },
        { uuid::TenorRecorder,                  SoundID::windFlutesRecorderTenor },
        { uuid::BassRecorder,                   SoundID::windFlutesRecorderBass },
        { uuid::DescantRecorder,                SoundID::windFlutesRecorderDescant },
        { uuid::Ocarina,                        SoundID::windFlutesOcarina },
        { uuid::PennyWhistle,                   SoundID::windFlutesWhistleTin },
        { uuid::PennyWhistleD,                  SoundID::windFlutesWhistleTinD },
        { uuid::PennyWhistleG,                  SoundID::windFlutesWhistleTin },
        { uuid::LowIrishWhistle,                SoundID::windFlutesWhistleLowIrish },
        { uuid::TinWhistleBFlat,                SoundID::windFlutesWhistleTinBflat },
        { uuid::Harmonica,                      SoundID::windReedHarmonica },
        { uuid::BassHarmonica,                  SoundID::windReedHarmonicaBass },
        { uuid::Concertina,                     SoundID::keyboardConcertina },
        { uuid::Bandoneon,                      SoundID::keyboardBandoneon },
        { uuid::HornF_WWQuintet,                SoundID::brassFrenchHorn },
        { uuid::Bagpipes,                       SoundID::windPipesBagpipes },
        { uuid::UilleannPipes,                  SoundID::windPipesUilleann },
        { uuid::GaidaPipes,                     SoundID::windPipesGaida },
        { uuid::ContraAltoFlute,                SoundID::windFlutesFluteContraAlto },
        { uuid::BassFlute,                      SoundID::windFlutesFluteBass },
        { uuid::ContrabassFlute,                SoundID::windFlutesFluteContrabass },
        { uuid::DoubleContrabassFlute,          SoundID::windFlutesFluteDoubleContrabass },
        { uuid::HyperbassFlute,                 SoundID::windFlutesFluteContrabass },
        { uuid::PanPipes,                       SoundID::windFlutesPanpipes },
        { uuid::Fife,                           SoundID::windFlutesFife },
        { uuid::BottleBlow,                     SoundID::windFlutesBlownBottle },
        { uuid::Jug,                            SoundID::windFlutesBlownBottle },
        { uuid::PiccoloOboe,                    SoundID::windReedOboePiccolo },
        { uuid::PiccoloHeckelphone,             SoundID::windReedHeckelphonePiccolo },
        { uuid::Heckelphone,                    SoundID::windReedHeckelphone },
        { uuid::BassOboe,                       SoundID::windReedOboeBass },
        { uuid::BassetClarinet,                 SoundID::windReedClarinetBasset },
        { uuid::BassetHorn,                     SoundID::windReedBassetHorn },
        { uuid::Hornpipe,                       SoundID::windReedHornpipe },
        { uuid::PiccoloClarinet,                SoundID::windReedClarinetPiccolo },
        { uuid::Saxonette,                      SoundID::windReedSaxonette },
        { uuid::SopraninoSax,                   SoundID::windReedSaxophoneSopranino },
        { uuid::MezzoSopranoSax,                SoundID::windReedSaxophoneMezzoSoprano },
        { uuid::Sopranino,                      SoundID::windReedSaxophoneSopranissimo },
        { uuid::CMelodySax,                     SoundID::windReedSaxophoneMelody },
        { uuid::Aulochrome,                     SoundID::windReedSaxophoneAulochrome },
        { uuid::Xaphoon,                        SoundID::windReedXaphoon },
        { uuid::BassSax,                        SoundID::windReedSaxophoneBass },
        { uuid::ContrabassSax,                  SoundID::windReedSaxophoneContrabass },
        { uuid::SubContrabassSax,               SoundID::windReedSaxophoneSubcontrabass },
        { uuid::Tubax,                          SoundID::windReedTubax },
        { uuid::Bansuri,                        SoundID::windFlutesBansuri },
        { uuid::Danso,                          SoundID::windFlutesDanso },
        { uuid::Dizi,                           SoundID::windFlutesDiZi },
        { uuid::DilliKaval,                     SoundID::windFlutesKaval },
        { uuid::Diple,                          SoundID::windReedDiple },
        // { uuid::DoubleFlute,                    SoundID:: },   // unmapped even in Finale
        { uuid::Dvojnice,                       SoundID::windFlutesDvojnice },
        { uuid::DvojniceDrone,                  SoundID::windFlutesDvojnice },
        { uuid::Flageolet,                      SoundID::windFlutesFlageolet },
        { uuid::Fujara,                         SoundID::windFlutesFujara },
        { uuid::Gemshorn,                       SoundID::windFlutesGemshorn },
        { uuid::Hocchiku,                       SoundID::windFlutesHocchiku },
        { uuid::Hun,                            SoundID::windFlutesHun },
        { uuid::IrishFlute,                     SoundID::windFlutesFluteIrish },
        { uuid::Kaval,                          SoundID::windFlutesKaval },
        { uuid::Khlui,                          SoundID::windFlutesKhlui },
        { uuid::KnotweedFlute,                  SoundID::windFlutesKnotweed },
        { uuid::KoncovkaAltoFlute,              SoundID::windFlutesKoncovkaAlto },
        { uuid::Koudi,                          SoundID::windFlutesKoudi },
        { uuid::Ney,                            SoundID::windFlutesNey },
        { uuid::Nohkan,                         SoundID::windFlutesNohkan },
        { uuid::NoseFlute,                      SoundID::windFlutesNose },
        { uuid::Palendag,                       SoundID::windFlutesPalendag },
        { uuid::Quena,                          SoundID::windFlutesQuena },
        { uuid::Ryuteki,                        SoundID::windFlutesRyuteki },
        { uuid::Shakuhachi,                     SoundID::windFlutesShakuhachi },
        { uuid::ShepherdsPipe,                  SoundID::windFlutesShepherdsPipe },
        { uuid::Shinobue,                       SoundID::windFlutesShinobue },
        { uuid::ShivaWhistle,                   SoundID::windFlutesWhistleShiva },
        { uuid::Shvi,                           SoundID::windFlutesShvi },
        { uuid::Suling,                         SoundID::windFlutesSuling },
        { uuid::Tarka,                          SoundID::windFlutesTarka },
        { uuid::TenorOvertoneFlute,             SoundID::windFlutesOvertoneTenor },
        { uuid::Tumpong,                        SoundID::windFlutesTumpong },
        { uuid::Venu,                           SoundID::windFlutesVenu },
        { uuid::Xiao,                           SoundID::windFlutesXiao },
        { uuid::Xun,                            SoundID::windFlutesXun },
        { uuid::Albogue,                        SoundID::windReedAlbogue },
        { uuid::Alboka,                         SoundID::windReedAlboka },
        { uuid::AltoCrumhorn,                   SoundID::windReedCrumhornAlto },
        { uuid::Arghul,                         SoundID::windReedArghul },
        { uuid::Bawu,                           SoundID::windReedBawu },
        { uuid::Chalumeau,                      SoundID::windReedChalumeau },
        { uuid::ClarinetteDAmour,               SoundID::windReedClarinetteDamour },
        { uuid::Cornamuse,                      SoundID::windReedCornamuse },
        { uuid::Diplica,                        SoundID::windReedDiplica },
        { uuid::DoubleClarinet,                 SoundID::windReedClarinet },
        { uuid::HeckelClarina,                  SoundID::windReedHeckelClarina },
        { uuid::HeckelphoneClarinet,            SoundID::windReedHeckelphoneClarinet },
        { uuid::Hirtenschalmei,                 SoundID::windReedHirtenschalmei },
        { uuid::Launeddas,                      SoundID::windReedLauneddas },
        { uuid::Maqrunah,                       SoundID::windReedMaqrunah },
        { uuid::Mijwiz,                         SoundID::windReedMijwiz },
        { uuid::Octavin,                        SoundID::windReedOctavin },
        { uuid::Pibgorn,                        SoundID::windReedPibgorn },
        { uuid::Rauschpfeife,                   SoundID::windReedRauschpfeife },
        { uuid::Sipsi,                          SoundID::windReedSipsi },
        { uuid::ModernTarogato,                 SoundID::windReedTarogato },
        { uuid::TenorCrumhorn,                  SoundID::windReedCrumhornTenor },
        { uuid::Zhaleika,                       SoundID::windReedZhaleika },
        { uuid::Algaita,                        SoundID::windReedAlgaita },
        { uuid::Bifora,                         SoundID::windReedBifora },
        { uuid::Bombarde,                       SoundID::windReedBombarde },
        { uuid::Cromorne,                       SoundID::windReedCromorne },
        { uuid::Duduk,                          SoundID::windReedDuduk },
        { uuid::Dulcian,                        SoundID::windReedDulcian },
        { uuid::Dulzaina,                       SoundID::windReedDulzaina },
        { uuid::Guan,                           SoundID::windReedGuanzi },
        { uuid::Guanzi,                         SoundID::windReedGuanzi },
        { uuid::Hichiriki,                      SoundID::windReedHichiriki },
        { uuid::Hne,                            SoundID::windReedHne },
        { uuid::JogiBaja,                       SoundID::windReedJogiBaja },
        { uuid::KenBau,                         SoundID::windReedKenBau },
        { uuid::Mizmar,                         SoundID::windReedMizmar },
        { uuid::Nadaswaram,                     SoundID::windReedNadaswaram },
        { uuid::OboeDaCaccia,                   SoundID::windReedOboeDaCaccia },
        { uuid::Pi,                             SoundID::windReedPi },
        { uuid::Piri,                           SoundID::windReedPiri },
        { uuid::PungiSnakeCharmer,              SoundID::windPungi },
        { uuid::Rackett,                        SoundID::windReedRackett },
        { uuid::ReedContrabass,                 SoundID::windReedContrabass },
        { uuid::Rhaita,                         SoundID::windReedRhaita },
        { uuid::Rothphone,                      SoundID::windReedRothphone },
        { uuid::Sarrusophone,                   SoundID::windReedSarrusaphone },
        { uuid::Shawm,                          SoundID::windReedShawm },
        { uuid::Shehnai,                        SoundID::windReedShenai },
        { uuid::Sopila,                         SoundID::windReedSopila },
        { uuid::Sorna,                          SoundID::windReedSorna },
        { uuid::Sralai,                         SoundID::windReedSralai },
        { uuid::Suona,                          SoundID::windReedSuona },
        { uuid::Surnay,                         SoundID::windReedSurnai },
        { uuid::Taepyeongso,                    SoundID::windReedTaepyeongso },
        { uuid::AncientTarogato,                SoundID::windReedTarogatoAncient },
        { uuid::TrompetaChina,                  SoundID::windReedTrompetaChina },
        { uuid::Zurla,                          SoundID::windReedZurla },
        { uuid::Zurna,                          SoundID::windReedZurna },
        { uuid::KhaenMouthOrgan,                SoundID::windReedKhaenMouthOrgan },
        { uuid::Hulusi,                         SoundID::windReedHulusi },
        { uuid::Sheng,                          SoundID::windReedSheng },

        // Brass
        { uuid::TrumpetBFlat,                   SoundID::brassTrumpetBflat },
        { uuid::TrumpetC,                       SoundID::brassTrumpetC },
        { uuid::TrumpetD,                       SoundID::brassTrumpetD },
        { uuid::Cornet,                         SoundID::brassCornet },
        { uuid::Flugelhorn,                     SoundID::brassFlugelhorn },
        { uuid::Mellophone,                     SoundID::brassMellophone },
        { uuid::HornF,                          SoundID::brassFrenchHorn },
        { uuid::Trombone,                       SoundID::brassTrombone },
        { uuid::BassTrombone,                   SoundID::brassTromboneBass },
        { uuid::Euphonium,                      SoundID::brassEuphonium },
        { uuid::BaritoneBC,                     SoundID::brassBaritoneHorn },
        { uuid::BaritoneTC,                     SoundID::brassBaritoneHorn },
        { uuid::Tuba,                           SoundID::brassTuba },
        { uuid::BassTuba,                       SoundID::brassTubaBass },
        { uuid::Sousaphone,                     SoundID::brassSousaphone },
        { uuid::BrassSection,                   SoundID::brassGroup },
        { uuid::PiccoloTrumpetA,                SoundID::brassTrumpetPiccolo },
        { uuid::Bugle,                          SoundID::brassBugle },
        { uuid::CornetEFlat,                    SoundID::brassCornet },
        { uuid::HornEFlat,                      SoundID::brassFrenchHorn },
        { uuid::AltoTrombone,                   SoundID::brassTromboneAlto },
        { uuid::TenorTrombone,                  SoundID::brassTromboneTenor },
        { uuid::ContrabassTrombone,             SoundID::brassTromboneContrabass },
        { uuid::Alphorn,                        SoundID::brassAlphorn },
        { uuid::AltoHorn,                       SoundID::brassAltoHorn },
        { uuid::Didgeridoo,                     SoundID::brassDidgeridoo },
        { uuid::PostHorn,                       SoundID::brassPosthorn },
        { uuid::ViennaHorn,                     SoundID::brassViennaHorn },
        { uuid::WagnerTuba,                     SoundID::brassWagnerTuba },
        { uuid::BaroqueTrumpet,                 SoundID::brassTrumpetBaroque },
        { uuid::BassTrumpet,                    SoundID::brassTrumpetBass },
        { uuid::Cornetto,                       SoundID::brassCornett },
        { uuid::Fiscorn,                        SoundID::brassFiscorn },
        { uuid::Kuhlohorn,                      SoundID::brassKuhlohorn },
        { uuid::PocketTrumpet,                  SoundID::brassTrumpetPocket },
        { uuid::Saxhorn,                        SoundID::brassSaxhorn },
        { uuid::SlideTrumpet,                   SoundID::brassTrumpetSlide },
        { uuid::Cimbasso,                       SoundID::brassCimbasso },
        { uuid::DoubleBellEuphonium,            SoundID::brassEuphonium },
        { uuid::Sackbut,                        SoundID::brassSackbutt },
        { uuid::Helicon,                        SoundID::brassHelicon },
        { uuid::Ophicleide,                     SoundID::brassOphicleide },
        { uuid::Serpent,                        SoundID::brassSerpent },
        { uuid::SubContrabassTuba,              SoundID::brassTubaSubcontrabass },
        { uuid::ConchShell,                     SoundID::brassConchShell },
        { uuid::Horagai,                        SoundID::brassHoragai },
        { uuid::Shofar,                         SoundID::brassShofar },
        { uuid::Vuvuzela,                       SoundID::brassVuvuzela },

        // Plucked Strings
        { uuid::Harp,                           SoundID::pluckHarp },
        { uuid::TroubadorHarp,                  SoundID::pluckHarp },
        { uuid::Guitar,                         SoundID::pluckGuitar },
        { uuid::Guitar8vb,                      SoundID::pluckGuitar },
        { uuid::AcousticGuitar,                 SoundID::pluckGuitarAcoustic },
        { uuid::ClassicalGuitar,                SoundID::pluckGuitarNylonString },
        { uuid::ElectricGuitar,                 SoundID::pluckGuitarElectric },
        { uuid::SteelGuitar,                    SoundID::pluckGuitarSteelString },
        { uuid::Banjo,                          SoundID::pluckBanjo },
        { uuid::TenorBanjo,                     SoundID::pluckBanjoTenor },
        { uuid::AcousticBass,                   SoundID::pluckBassAcoustic },
        { uuid::BassGuitar,                     SoundID::pluckBass },
        { uuid::ElectricBass,                   SoundID::pluckBassElectric },
        { uuid::FretlessBass,                   SoundID::pluckBassFretless },
        { uuid::StringBass,                     SoundID::stringsContrabass },
        { uuid::Mandolin,                       SoundID::pluckMandolin },
        { uuid::Dulcimer,                       SoundID::pluckDulcimer },
        { uuid::HammeredDulcimer,               SoundID::pitchedPercussionHammerDulcimer },
        { uuid::Dulcimer8vb,                    SoundID::pluckDulcimer },
        { uuid::Autoharp,                       SoundID::pluckAutoharp },
        { uuid::Lute,                           SoundID::pluckLute },
        { uuid::Ukulele,                        SoundID::pluckUkulele },
        { uuid::TenorUkulele,                   SoundID::pluckUkuleleTenor },
        { uuid::Sitar,                          SoundID::pluckSitar },
        { uuid::Zither,                         SoundID::pluckZither },
        { uuid::Archlute,                       SoundID::pluckArchlute },
        { uuid::Baglama,                        SoundID::pluckBaglama },
        { uuid::Balalaika,                      SoundID::pluckBalalaika },
        { uuid::Bandura,                        SoundID::pluckBandura },
        { uuid::Banjolele,                      SoundID::pluckBanjolele },
        { uuid::Barbat,                         SoundID::pluckBarbat },
        { uuid::Begena,                         SoundID::pluckBegena },
        { uuid::Biwa,                           SoundID::pluckBiwa },
        { uuid::Bolon,                          SoundID::pluckBassBolon },
        { uuid::Bordonua,                       SoundID::pluckBordonua },
        { uuid::Bouzouki,                       SoundID::pluckBouzouki },
        { uuid::BulgarianTambura,               SoundID::pluckTamburaBulgarian },
        { uuid::ChapmanStick,                   SoundID::pluckSynthStick },
        { uuid::Charango,                       SoundID::pluckCharango },
        { uuid::ChitarraBattente,               SoundID::pluckChitarraBattente },
        { uuid::ChaozhouGuzheng,                SoundID::pluckGuzhengChoazhou },
        { uuid::Cimbalom,                       SoundID::pitchedPercussionCimbalom },
        { uuid::Cittern,                        SoundID::pluckCittern },
        { uuid::Cuatro,                         SoundID::pluckCuatro },
        { uuid::DanBau,                         SoundID::pluckDanBau },
        { uuid::DanNguyet,                      SoundID::pluckDanNguyet },
        { uuid::DanTamThapLuc,                  SoundID::pitchedPercussionDanTamThapLuc },
        { uuid::DanTranh,                       SoundID::pluckDanTranh },
        { uuid::DanTyBa,                        SoundID::pluckDanTyBa },
        { uuid::DiddleyBow,                     SoundID::pluckDiddleyBow },
        { uuid::Dobro,                          SoundID::pluckGuitarResonator },
        { uuid::Domra,                          SoundID::pluckDomra },
        { uuid::Dutar,                          SoundID::pluckDutar },
        { uuid::Duxianqin,                      SoundID::pluckDuxianqin },
        { uuid::Ektara1,                        SoundID::pluckEktara },
        { uuid::FlamencoGuitar,                 SoundID::pluckGuitarNylonString },
        { uuid::Geomungo,                       SoundID::pluckGeomungo },
        { uuid::Ektara2,                        SoundID::pluckEktara },
        { uuid::Gottuvadhyam,                   SoundID::pluckGottuvadhyam },
        { uuid::GuitarraQuintaHuapanguera,      SoundID::pluckHuapanguera },
        { uuid::Guitarron,                      SoundID::pluckBassGuitarron },
        { uuid::Guitjo,                         SoundID::pluckGuitjo },
        { uuid::GuitjoDoubleNeck,               SoundID::pluckGuitjoDoubleNeck },
        { uuid::Guqin,                          SoundID::pluckGuqin },
        { uuid::Guzheng,                        SoundID::pluckGuzheng },
        { uuid::HarpGuitar,                     SoundID::pluckHarpGuitar },
        { uuid::IrishBouzouki,                  SoundID::pluckBouzoukiIrish },
        { uuid::JaranaHuasteca,                 SoundID::pluckJaranaHuasteca },
        { uuid::JaranaJarocho,                  SoundID::pluckJaranaJarocha },
        { uuid::JaranaMosquito,                 SoundID::pluckJaranaJarochaMosquito },
        { uuid::JaranaSegunda,                  SoundID::pluckJaranaJarochaSegunda },
        { uuid::JaranaTercera,                  SoundID::pluckJaranaJarochaTercera },
        { uuid::Kabosy,                         SoundID::pluckKabosy },
        { uuid::Kantele,                        SoundID::pluckKantele },
        { uuid::Kayagum,                        SoundID::pluckKayagum },
        { uuid::Khim,                           SoundID::pitchedPercussionKhim },
        { uuid::Kobza,                          SoundID::pluckKobza },
        { uuid::Komuz,                          SoundID::pluckKomuz },
        { uuid::Koto,                           SoundID::pluckKoto },
        { uuid::Kutiyapi,                       SoundID::pluckKutiyapi },
        { uuid::Langeleik,                      SoundID::pluckLangeleik },
        { uuid::Lyre,                           SoundID::pluckLyre },
        { uuid::MandoBass,                      SoundID::pluckMandobass },
        { uuid::MandoCello,                     SoundID::pluckMandocello },
        { uuid::Mandola,                        SoundID::pluckMandola },
        { uuid::Mandora,                        SoundID::pluckMandora },
        { uuid::Mandore,                        SoundID::pluckMandore },
        { uuid::Mangbetu,                       SoundID::pluckDomu },
        { uuid::Marovany,                       SoundID::pluckMarovany },
        { uuid::MohanVeena,                     SoundID::pluckVeenaMohan },
        { uuid::MoodSwinger,                    SoundID::pluckZitherOvertone },
        { uuid::MusicalBow,                     SoundID::pluckMusicalBow },
        { uuid::Ngoni,                          SoundID::pluckNgoni },
        { uuid::OctaveMandolin,                 SoundID::pluckMandolinOctave },
        { uuid::Oud,                            SoundID::pluckOud },
        { uuid::Pipa,                           SoundID::pluckPipa },
        { uuid::PortugueseGuitar,               SoundID::pluckGuitarPortuguese },
        { uuid::Psaltery,                       SoundID::pluckPsaltery },
        { uuid::RequintoGuitar,                 SoundID::pluckGuitarRequinto },
        { uuid::Ruan,                           SoundID::pluckRuan },
        { uuid::RudraVeena,                     SoundID::pluckVeenaRudra },
        { uuid::Sallaneh,                       SoundID::pluckSallaneh },
        { uuid::Sanshin,                        SoundID::pluckSanshin },
        { uuid::Santoor,                        SoundID::pluckSantoor },
        { uuid::Sanxian,                        SoundID::pluckSanxian },
        { uuid::Sarod,                          SoundID::pluckSarod },
        { uuid::Saung,                          SoundID::pluckSaung },
        { uuid::Saz,                            SoundID::pluckSaz },
        { uuid::Se,                             SoundID::pluckSe },
        { uuid::Setar,                          SoundID::pluckSetar },
        { uuid::Shamisen,                       SoundID::pluckShamisen },
        { uuid::Tambura,                        SoundID::pluckTambura },
        { uuid::TarPlucked,                     SoundID::pluckTar },
        { uuid::Theorbo,                        SoundID::pluckTheorbo },
        { uuid::Timple,                         SoundID::pluckTimple },
        { uuid::Tres,                           SoundID::pluckTres },
        { uuid::Tsymbaly,                       SoundID::pitchedPercussionTsymbaly },
        { uuid::Valiha,                         SoundID::pluckValiha },
        { uuid::Veena,                          SoundID::pluckVeena },
        { uuid::VichitraVeena,                  SoundID::pluckVeenaVichitra },
        { uuid::VihuelaMexico,                  SoundID::pluckVihuelaMexican },
        { uuid::VihuelaSpain,                   SoundID::pluckVihuela },
        { uuid::WashtubBass,                    SoundID::pluckBassWashtub },
        { uuid::Whamola,                        SoundID::pluckBassWhamola },
        { uuid::Xalam,                          SoundID::pluckXalam },
        { uuid::Yangqin,                        SoundID::pitchedPercussionYangqin },
        { uuid::Yazheng,                        SoundID::stringsYazheng },
        { uuid::Yueqin,                         SoundID::pluckYueqin },
        { uuid::TabGuitar,                      SoundID::pluckGuitar },
        { uuid::TabGuitarNoName,                SoundID::pluckGuitar },
        { uuid::TabGuitarStems,                 SoundID::pluckGuitar },
        { uuid::TabGuitarD,                     SoundID::pluckGuitar },
        { uuid::TabGuitarDADGAD,                SoundID::pluckGuitar },
        { uuid::TabGuitarDoubled,               SoundID::pluckGuitar },
        { uuid::TabGuitarDropD,                 SoundID::pluckGuitar },
        { uuid::TabGuitarG,                     SoundID::pluckGuitar },
        { uuid::TabGuitar7String,               SoundID::pluckGuitar },
        { uuid::TabBanjoG,                      SoundID::pluckBanjo },
        { uuid::TabTenorBanjo,                  SoundID::pluckBanjoTenor },
        { uuid::TabBanjoC,                      SoundID::pluckBanjo },
        { uuid::TabBanjoD,                      SoundID::pluckBanjo },
        { uuid::TabBanjoDoubleC,                SoundID::pluckBanjo },
        { uuid::TabBanjoGModal,                 SoundID::pluckBanjo },
        { uuid::TabBanjoPlectrum,               SoundID::pluckBanjo },
        { uuid::TabBassGuitar4,                 SoundID::pluckBass },
        { uuid::TabBassGuitar5,                 SoundID::pluckBass },
        { uuid::TabBassGuitar6,                 SoundID::pluckBass },
        { uuid::TabDulcimerDAA,                 SoundID::pluckDulcimer },
        { uuid::TabDulcimerDAAUnison,           SoundID::pluckDulcimer },
        { uuid::TabDulcimerDAD,                 SoundID::pluckDulcimer },
        { uuid::TabGamba,                       SoundID::stringsViol },
        { uuid::TabLuteItalian,                 SoundID::pluckLute },
        { uuid::TabLuteLetters,                 SoundID::pluckLute },
        { uuid::TabMandolin,                    SoundID::pluckMandolin },
        { uuid::TabRequinto,                    SoundID::pluckGuitarRequinto },
        { uuid::TabSitarShankar,                SoundID::pluckSitar },
        { uuid::TabSitarKhan,                   SoundID::pluckSitar },
        { uuid::TabUkulele,                     SoundID::pluckUkulele },
        { uuid::TabVihuela,                     SoundID::pluckVihuela },

        // Pitched Percussion
        { uuid::Timpani,                        SoundID::drumTimpani },
        // { uuid::Mallets,                        SoundID:: },   // unmapped even in Finale
        { uuid::Bells,                          SoundID::pitchedPercussionBells },
        { uuid::Chimes,                         SoundID::metalBellsChimes },
        { uuid::Crotales,                       SoundID::metalCrotales },
        { uuid::Glockenspiel,                   SoundID::pitchedPercussionGlockenspiel },
        { uuid::SopranoGlockenspiel,            SoundID::pitchedPercussionGlockenspielSoprano },
        { uuid::AltoGlockenspiel,               SoundID::pitchedPercussionGlockenspielAlto },
        { uuid::Marimba,                        SoundID::pitchedPercussionMarimba },
        { uuid::BassMarimba,                    SoundID::pitchedPercussionMarimbaBass },
        { uuid::MarimbaSingleStaff,             SoundID::pitchedPercussionMarimba },
        { uuid::TubularBells,                   SoundID::pitchedPercussionTubularBells },
        { uuid::Vibraphone,                     SoundID::pitchedPercussionVibraphone },
        { uuid::Xylophone,                      SoundID::pitchedPercussionXylophone },
        { uuid::SopranoXylophone,               SoundID::pitchedPercussionXylophoneSoprano },
        { uuid::AltoXylophone,                  SoundID::pitchedPercussionXylophoneAlto },
        { uuid::BassXylophone,                  SoundID::pitchedPercussionXylophoneBass },
        { uuid::Xylorimba,                      SoundID::pitchedPercussionXylorimba },
        { uuid::BellLyre,                       SoundID::pitchedPercussionBellLyre },
        { uuid::Boomwhackers,                   SoundID::pitchedPercussionTubes },
        { uuid::ChromanotesInstruments,         SoundID::pitchedPercussionTubes },
        { uuid::Carillon,                       SoundID::metalBellsCarillon },
        { uuid::CrystalGlasses,                 SoundID::pitchedPercussionCrystalGlasses },
        { uuid::FlexatonePitched,               SoundID::metalFlexatone },
        { uuid::GlassHarmonica,                 SoundID::pitchedPercussionGlassHarmonica },
        { uuid::GlassMarimba,                   SoundID::pitchedPercussionMarimba },
        { uuid::Handbells,                      SoundID::pitchedPercussionHandbells },
        { uuid::HandbellsTClef,                 SoundID::pitchedPercussionHandbells },
        { uuid::HandbellsBClef,                 SoundID::pitchedPercussionHandbells },
        { uuid::HangTClef,                      SoundID::metalHang },
        { uuid::JawHarp,                        SoundID::metalJawHarp },
        { uuid::Kalimba,                        SoundID::pitchedPercussionKalimba },
        { uuid::SopranoMetallophone,            SoundID::pitchedPercussionMetallophoneSoprano },
        { uuid::AltoMetallophone,               SoundID::pitchedPercussionMetallophoneAlto },
        { uuid::BassMetallophone,               SoundID::pitchedPercussionMetallophoneBass },
        { uuid::MusicalSaw,                     SoundID::metalMusicalSaw },
        { uuid::SlideWhistle,                   SoundID::windFlutesWhistleSlide },
        { uuid::SteelDrumsTClef,                SoundID::metalSteelDrums },
        { uuid::SteelDrumsBClef,                SoundID::metalSteelDrums },
        { uuid::BonangGamelan,                  SoundID::pitchedPercussionBonang },
        { uuid::GansaGamelan,                   SoundID::pitchedPercussionGangsa },
        { uuid::GenderGamelan,                  SoundID::pitchedPercussionGender },
        { uuid::GiyingGamelan,                  SoundID::pitchedPercussionGiying },
        { uuid::KantilGamelan,                  SoundID::pitchedPercussionKantil },
        { uuid::PelogPanerusGamelan,            SoundID::pitchedPercussionPelogPanerus },
        { uuid::PemadeGamelan,                  SoundID::pitchedPercussionPemade },
        { uuid::PenyacahGamelan,                SoundID::pitchedPercussionPenyacah },
        { uuid::SaronBarungGamelan,             SoundID::pitchedPercussionSaronBarung },
        { uuid::SaronDemongGamelan,             SoundID::pitchedPercussionSaronDemong },
        { uuid::SaronPanerusGamelan,            SoundID::pitchedPercussionSaronPanerus },
        { uuid::SlendroPanerusGamelan,          SoundID::pitchedPercussionSlendroPanerus },
        { uuid::SlenthemGamelan,                SoundID::pitchedPercussionSlentem },
        { uuid::Almglocken,                     SoundID::metalBellsAlmglocken },
        { uuid::Angklung,                       SoundID::pitchedPercussionAngklung },
        { uuid::ArrayMbira,                     SoundID::pitchedPercussionMbiraArray },
        { uuid::Balafon,                        SoundID::pitchedPercussionBalafon },
        { uuid::Balaphon,                       SoundID::pitchedPercussionBalafon },
        { uuid::Bianqing,                       SoundID::pitchedPercussionBianqing },
        { uuid::Bianzhong,                      SoundID::pitchedPercussionBianzhong },
        { uuid::Fangxiang,                      SoundID::pitchedPercussionFangxiang },
        { uuid::GandinganAKayo,                 SoundID::pitchedPercussionGandinganAKayo },
        { uuid::Gyil,                           SoundID::pitchedPercussionGyil },
        { uuid::Kubing,                         SoundID::woodKubing },
        { uuid::Kulintang,                      SoundID::pitchedPercussionKulintang },
        { uuid::KulintangAKayo,                 SoundID::pitchedPercussionKulintangAKayo },
        { uuid::KulintangATiniok,               SoundID::pitchedPercussionKulintangATiniok },
        { uuid::Lamellaphone,                   SoundID::pluckLute },   // mapping checked in Finale
        { uuid::Likembe,                        SoundID::pitchedPercussionLikembe },
        { uuid::Luntang,                        SoundID::pitchedPercussionLuntang },
        { uuid::Mbira,                          SoundID::pitchedPercussionMbira },
        { uuid::Murchang,                       SoundID::metalMurchang },
        { uuid::RanatEklek,                     SoundID::pitchedPercussionRanatEkLek },
        { uuid::RanatThumLek,                   SoundID::pitchedPercussionRanatThumLek },
        { uuid::Sanza,                          SoundID::pitchedPercussionSanza },
        { uuid::TaikoDrums,                     SoundID::drumTaiko },
        { uuid::TempleBells,                    SoundID::metalBellsTemple },
        { uuid::TibetanBells,                   SoundID::metalBellsTibetan },
        { uuid::TibetanSingingBowls,            SoundID::metalSingingBowl },
        { uuid::SnareDrum,                      SoundID::drumSnareDrum },
        { uuid::BassDrum,                       SoundID::drumBassDrum },
        { uuid::DrumSet,                        SoundID::drumGroupSet },
        { uuid::TenorDrum,                      SoundID::drumTenorDrum },
        { uuid::QuadToms,                       SoundID::drumTomTom },
        { uuid::QuintToms,                      SoundID::drumTomTom },
        { uuid::RotoToms,                       SoundID::drumRototom },
        { uuid::TenorLine,                      SoundID::drumTenorDrum },
        { uuid::SnareLine,                      SoundID::drumSnareDrum },
        { uuid::BassDrums5Line,                 SoundID::drumBassDrum },
        { uuid::Djembe,                         SoundID::drumDjembe },
        { uuid::BongoDrums,                     SoundID::drumBongo },
        { uuid::CongaDrums,                     SoundID::drumConga },
        { uuid::LogDrum,                        SoundID::drumLogDrum },
        { uuid::Tablas,                         SoundID::drumTabla },
        { uuid::Timbales,                       SoundID::drumTimbale },
        { uuid::AfricanLogDrum,                 SoundID::drumLogDrumAfrican },
        { uuid::Apentemma,                      SoundID::drumApentemma },
        { uuid::ArabianFrameDrum,               SoundID::drumFrameDrumArabian },
        { uuid::Ashiko,                         SoundID::drumAshiko },
        { uuid::Atabaque,                       SoundID::drumAtabaque },
        { uuid::Bata,                           SoundID::drumBata },
        { uuid::Bendir,                         SoundID::drumBendir },
        { uuid::Bodhran,                        SoundID::drumBodhran },
        { uuid::Bombo,                          SoundID::drumBombo },
        { uuid::Bougarabou,                     SoundID::drumBougarabou },
        { uuid::BuffaloDrum,                    SoundID::drumBuffaloDrum },
        { uuid::Chenda,                         SoundID::drumChenda },
        { uuid::Chudaiko,                       SoundID::drumChuDaiko },
        { uuid::Dabakan,                        SoundID::drumDabakan },
        { uuid::Daibyosi,                       SoundID::drumDaibyosi },
        { uuid::Damroo,                         SoundID::drumDamroo },
        { uuid::Darabuka,                       SoundID::drumDarabuka },
        { uuid::DatanguLionDrum,                SoundID::drumLionDrum },
        { uuid::Dhol,                           SoundID::drumDhol },
        { uuid::Dholak,                         SoundID::drumDholak },
        // { uuid::Dollu,                          SoundID:: },  // unmapped even in Finale
        { uuid::Dondo,                          SoundID::drumDondo },
        { uuid::Doundounba,                     SoundID::drumDounDounBa },
        { uuid::Duff,                           SoundID::drumDuff },
        { uuid::Dumbek,                         SoundID::drumDumbek },
        { uuid::EweDrumKagan,                   SoundID::drumKagan },
        { uuid::EweDrumKpanlogo1Large,          SoundID::drumKpanlogo },
        { uuid::EweDrumKpanlogo2Medium,         SoundID::drumKpanlogo },
        { uuid::EweDrumKpanlogo3Combo,          SoundID::drumKpanlogo },
        { uuid::EweDrumSogo,                    SoundID::drumSogo },
        { uuid::Fontomfrom,                     SoundID::drumFontomfrom },
        { uuid::Geduk,                          SoundID::drumGeduk },
        { uuid::HandDrum,                       SoundID::drumHandDrum },
        { uuid::Hiradaiko,                      SoundID::drumHiraDaiko },
        { uuid::Igihumurizo,                    SoundID::drumIgihumurizo },
        { uuid::Ingoma,                         SoundID::drumIshakwe },
        { uuid::Inyahura,                       SoundID::drumInyahura },
        { uuid::Janggu,                         SoundID::drumJangGu },
        { uuid::Kakko,                          SoundID::drumKakko },
        { uuid::Kanjira,                        SoundID::drumKanjira },
        { uuid::KendangGamelan,                 SoundID::drumKendhang },
        { uuid::Kenkeni,                        SoundID::drumKenkeni },
        { uuid::Khol,                           SoundID::drumKhol },
        { uuid::Kodaiko,                        SoundID::drumKoDaiko },
        { uuid::Kudum,                          SoundID::drumKudum },
        { uuid::LambegDrum,                     SoundID::drumLambeg },
        { uuid::Madal,                          SoundID::drumMadal },
        { uuid::Maddale,                        SoundID::drumMaddale },
        { uuid::MoroccoDrum,                    SoundID::drumFrameDrum },
        { uuid::Mridangam,                      SoundID::drumMridangam },
        { uuid::Naal,                           SoundID::drumNaal },
        { uuid::NagaDodaiko,                    SoundID::drumNagadoDaiko },
        { uuid::Nagara,                         SoundID::drumNagara },
        { uuid::Naqara,                         SoundID::drumNaqara },
        { uuid::NativeLogDrum,                  SoundID::drumLogDrumNative },
        { uuid::NigerianLogDrum,                SoundID::drumLogDrumNigerian },
        { uuid::Odaiko,                         SoundID::drumODaiko },
        { uuid::Okawa,                          SoundID::drumOkawa },
        { uuid::OkedoDodaiko,                   SoundID::drumOkedoDaiko },
        { uuid::PahuHula,                       SoundID::drumPahuHula },
        { uuid::Pakhavaj,                       SoundID::drumPakhawaj },
        { uuid::Pandero,                        SoundID::drumPandero },
        { uuid::PowwowDrum,                     SoundID::drumPowwow },
        { uuid::PuebloDrum,                     SoundID::drumPueblo },
        { uuid::Repinique,                      SoundID::drumRepinique },
        { uuid::Sabar,                          SoundID::drumSabar },
        { uuid::Sakara,                         SoundID::drumSakara },
        { uuid::Sampho,                         SoundID::drumSampho },
        { uuid::Sangban,                        SoundID::drumSangban },
        { uuid::ShimeDaiko,                     SoundID::drumShimeDaiko },
        { uuid::Surdo,                          SoundID::drumSurdo },
        { uuid::TalkingDrum,                    SoundID::drumTalking },
        { uuid::Tama,                           SoundID::drumTama },
        { uuid::Tamborita,                      SoundID::drumTamborita },
        { uuid::Tamte,                          SoundID::drumTamte },
        { uuid::Tantan,                         SoundID::drumTanTan },
        { uuid::Tangku,                         SoundID::drumTangku },
        { uuid::Taphon,                         SoundID::drumTaphon },
        { uuid::TarDrum,                        SoundID::drumTar },
        { uuid::Tasha,                          SoundID::drumTasha },
        { uuid::Thavil,                         SoundID::drumThavil },
        { uuid::Tombak,                         SoundID::drumTombak },
        { uuid::Tumbak,                         SoundID::drumTumbak },
        { uuid::Tsuzumi,                        SoundID::drumTsuzumi },
        { uuid::UchiwaDaiko,                    SoundID::drumUchiwaDaiko },
        { uuid::Udaku,                          SoundID::drumUdaku },
        { uuid::Zarb,                           SoundID::drumZarb },

        // Percussion
        { uuid::PercussionGeneral,              SoundID::drumGroupSet },
        // { uuid::PercAccessories,                SoundID:: },   // unmapped even in Finale
        { uuid::WindChimes,                     SoundID::metalBellsWindChimes },
        { uuid::ChimeTree,                      SoundID::metalBellsMarkTree },
        { uuid::BellTree,                       SoundID::metalBellsBellTree },
        { uuid::JingleBells,                    SoundID::metalBellsJingleBell },
        { uuid::Tambourine,                     SoundID::drumTambourine },
        { uuid::Triangle,                       SoundID::metalTriangle },
        { uuid::Cymbals,                        SoundID::metalCymbalCrash },
        { uuid::FingerCymbals,                  SoundID::metalCymbalFinger },
        { uuid::CrashCymbal,                    SoundID::metalCymbalCrash },
        { uuid::HiHatCymbal,                    SoundID::metalHiHat },
        { uuid::RideCymbal,                     SoundID::metalCymbalRide },
        { uuid::SplashCymbal,                   SoundID::metalCymbalSplash },
        { uuid::TamTam,                         SoundID::metalTamtam },
        { uuid::Gong,                           SoundID::metalGong },
        { uuid::AgogoBells,                     SoundID::metalBellsAgogo },
        { uuid::AirHorn,                        SoundID::effectAirHorn },
        { uuid::BrakeDrum,                      SoundID::metalBrakeDrums },
        { uuid::Cabasa,                         SoundID::rattleCabasa },
        { uuid::Cajon,                          SoundID::drumCajon },
        { uuid::Castanets,                      SoundID::woodCastanets },
        { uuid::Clap,                           SoundID::effectHandClap },
        { uuid::Clapper,                        SoundID::woodSlapstick },
        { uuid::Claves,                         SoundID::woodClaves },
        { uuid::Cowbell,                        SoundID::metalBellsCowbell },
        { uuid::Cuica,                          SoundID::drumCuica },
        { uuid::Guiro,                          SoundID::woodGuiro },
        { uuid::Maracas,                        SoundID::rattleMaraca },
        { uuid::PoliceWhistle,                  SoundID::effectWhistlePolice },
        { uuid::Rainstick,                      SoundID::rattleRainStick },
        { uuid::Ratchet,                        SoundID::rattleRatchet },
        { uuid::Rattle,                         SoundID::rattleRattle },
        { uuid::SandBlock,                      SoundID::woodSandBlock },
        { uuid::Shakers,                        SoundID::rattleShaker },
        { uuid::Spoons,                         SoundID::metalSpoons },
        { uuid::TempleBlocks,                   SoundID::woodTempleBlock },
        { uuid::Vibraslap,                      SoundID::rattleVibraslap },
        { uuid::Washboard,                      SoundID::metalWashboard },
        { uuid::Whip,                           SoundID::effectWhip },
        { uuid::WindMachine,                    SoundID::effectWind },
        { uuid::WoodBlocks,                     SoundID::woodWoodBlock },
        { uuid::CengCengGamelan,                SoundID::metalCymbalCengCeng },
        { uuid::GongAgengGamelan,               SoundID::metalGongAgeng },
        { uuid::KempulGamelan,                  SoundID::metalGongKempul },
        { uuid::KempyangGamelan,                SoundID::metalGongKempyang },
        { uuid::KenongGamelan,                  SoundID::metalKengong },
        { uuid::KetukGamelan,                   SoundID::metalGongKetuk },
        { uuid::ReyongGamelan,                  SoundID::pitchedPercussionReyong },
        { uuid::Adodo,                          SoundID::metalAdodo },
        { uuid::AeolianHarp,                    SoundID::effectAeolianHarp },
        { uuid::Afoxe,                          SoundID::rattleAfoxe },
        { uuid::AgogoBlock,                     SoundID::woodAgogoBlock },
        { uuid::Agung,                          SoundID::metalGongAgung },
        { uuid::AgungAtamLang,                  SoundID::woodAgungATamlang },
        { uuid::Ahoko,                          SoundID::woodAhoko },
        { uuid::Babendil,                       SoundID::metalBabendil },
        { uuid::BasicAfricanPercussion,         SoundID::drumGroup },
        { uuid::BasicIndianPercussion,          SoundID::drumGroupIndian },
        { uuid::BasicMiddleEastPercussion,      SoundID::drumGroup },
        { uuid::Berimbau,                       SoundID::metalBerimbau },
        { uuid::Bo,                             SoundID::metalCymbalBo },
        { uuid::Bones,                          SoundID::woodBones },
        { uuid::BongoBells,                     SoundID::metalBellsCowbell },
        { uuid::Bullroarer,                     SoundID::effectBullroarer },
        { uuid::Caxixi,                         SoundID::rattleCaxixi },
        { uuid::ChachaBells,                    SoundID::metalBellsCowbell },
        { uuid::Chabara,                        SoundID::metalCymbalChabara },
        { uuid::Chanchiki,                      SoundID::metalGongChanchiki },
        { uuid::Chimta,                         SoundID::metalBellsChimta },
        { uuid::ChinaTempleBlocks,              SoundID::woodTempleBlock },
        { uuid::ChineseCymbals,                 SoundID::metalCymbalChinese },
        { uuid::ChineseGongs,                   SoundID::metalGongChinese },
        { uuid::ChinesePercussionEnsemble,      SoundID::drumGroupChinese },
        { uuid::Ching,                          SoundID::metalCymbalChing },
        { uuid::Chippli,                        SoundID::metalBellsChippli },
        { uuid::Daff,                           SoundID::drumDaff },
        { uuid::Dafli,                          SoundID::drumDafli },
        { uuid::Dawuro,                         SoundID::metalBellsDawuro },
        { uuid::Def,                            SoundID::drumDef },
        { uuid::Doira,                          SoundID::drumDoira },
        { uuid::EweDrumAtoke,                   SoundID::drumAtoke },
        { uuid::EweDrumAxatse,                  SoundID::drumAxatse },
        { uuid::EweDrumGangokui,                SoundID::metalBellsGankokwe },
        { uuid::FlexatonePerc,                  SoundID::metalFlexatone },
        { uuid::Gandingan,                      SoundID::metalGongGandingan },
        { uuid::Ganza,                          SoundID::rattleGanza },
        { uuid::Ghatam,                         SoundID::drumGhatam },
        { uuid::Ghungroo,                       SoundID::metalBellsGhungroo },
        { uuid::Gome,                           SoundID::drumGome },
        { uuid::Guban,                          SoundID::woodGuban },
        { uuid::HandCymbal,                     SoundID::metalCymbalHand },
        { uuid::Hang,                           SoundID::metalHang },
        { uuid::Hatheli,                        SoundID::metalBellsHatheli },
        { uuid::Hosho,                          SoundID::rattleHosho },
        { uuid::Hyoushigi,                      SoundID::woodHyoushigi },
        { uuid::Ibo,                            SoundID::drumIbo },
        { uuid::IndianGong,                     SoundID::metalGong },
        { uuid::Ipu,                            SoundID::woodIpu },
        { uuid::Jawbone,                        SoundID::rattleJawbone },
        { uuid::KaEkeEke,                       SoundID::woodKaekeeke },
        { uuid::Kagul,                          SoundID::woodKagul },
        { uuid::Kalaau,                         SoundID::woodKalaau },
        { uuid::Kashiklar,                      SoundID::woodKashiklar },
        { uuid::Kesi,                           SoundID::metalCymbalKesi },
        { uuid::Khartal,                        SoundID::metalBellsKhartal },
        { uuid::Kkwaenggwari,                   SoundID::metalGongKkwenggwari },
        { uuid::Kpokopoko,                      SoundID::rattleKpokoKpoko },
        { uuid::KrinSlitDrum,                   SoundID::drumSlitDrumKrin },
        { uuid::LavaStones,                     SoundID::rattleLavaStones },
        { uuid::LuoGong,                        SoundID::metalGongLuo },
        { uuid::Manjeera,                       SoundID::metalCymbalManjeera },
        { uuid::PanClappers,                    SoundID::woodPanClappers },
        { uuid::Patschen,                       SoundID::effectPat },
        { uuid::RattleCog,                      SoundID::rattleCog },
        { uuid::Riq,                            SoundID::drumRiq },
        { uuid::Shekere,                        SoundID::rattleShekere },
        { uuid::Sistre,                         SoundID::rattleSistre },
        { uuid::Sistrum,                        SoundID::metalBellsSistrum },
        { uuid::SlideWhistlePercClef,           SoundID::effectWhistleSlide },
        { uuid::SlitDrum,                       SoundID::drumSlitDrum },
        { uuid::Snap,                           SoundID::effectSnap },
        { uuid::Stamp,                          SoundID::effectStamp },
        { uuid::StirDrum,                       SoundID::woodStirDrum },
        { uuid::TebYoshi,                       SoundID::metalCymbalTebyoshi },
        { uuid::Televi,                         SoundID::rattleTelevi },
        { uuid::Teponaztli,                     SoundID::drumTeponaxtli },
        { uuid::ThaiGong,                       SoundID::metalGongThai },
        { uuid::TibetanCymbals,                 SoundID::metalCymbalTibetan },
        { uuid::TicTocBlock,                    SoundID::woodTicTocBlock },
        { uuid::TimbaleBell,                    SoundID::drumTimbale },
        { uuid::Tinaja,                         SoundID::drumTinaja },
        { uuid::Tingsha,                        SoundID::metalCymbalTingsha },
        { uuid::Toere,                          SoundID::drumToere },
        { uuid::ToneTang,                       SoundID::woodTonetang },
        { uuid::Trychel,                        SoundID::metalBellsTrychel },
        { uuid::Udu,                            SoundID::drumUdu },
        { uuid::Zills,                          SoundID::metalBellsZills },
    });

    const auto iter = std::find_if(table.begin(), table.end(), [instUuid](const InstrumentSoundMapping& item) {
        return item.instUuid == instUuid;
    });
    if (iter == table.end()) {
        return std::nullopt;
    }
    return iter->soundId;
}

} // namespace detail
} // namespace musicxml
} // namespace formats
} // namespace denigma
