function(denigma_resolve_git_ref_commit output_variable repository ref)
    set(_resolved_commit "")
    if(ref MATCHES "^[0-9a-fA-F]{7,40}$")
        string(SUBSTRING "${ref}" 0 7 _resolved_commit)
    elseif(GIT_FOUND)
        execute_process(
            COMMAND "${GIT_EXECUTABLE}" ls-remote "${repository}" "${ref}" "refs/heads/${ref}" "refs/tags/${ref}" "refs/tags/${ref}^{}"
            OUTPUT_VARIABLE _ls_remote_output
            OUTPUT_STRIP_TRAILING_WHITESPACE
            RESULT_VARIABLE _ls_remote_result
            ERROR_QUIET
        )
        if(_ls_remote_result EQUAL 0 AND _ls_remote_output)
            string(REPLACE "\n" ";" _ls_remote_lines "${_ls_remote_output}")
            set(_best_priority 0)
            foreach(_line IN LISTS _ls_remote_lines)
                if(_line MATCHES "^([0-9a-fA-F]+)[ \t]+(.+)$")
                    set(_candidate_commit "${CMAKE_MATCH_1}")
                    set(_candidate_ref "${CMAKE_MATCH_2}")
                    set(_candidate_priority 0)
                    if(_candidate_ref STREQUAL "refs/tags/${ref}^{}")
                        set(_candidate_priority 4)
                    elseif(_candidate_ref STREQUAL "refs/heads/${ref}")
                        set(_candidate_priority 3)
                    elseif(_candidate_ref STREQUAL "refs/tags/${ref}")
                        set(_candidate_priority 2)
                    elseif(_candidate_ref STREQUAL "${ref}")
                        set(_candidate_priority 1)
                    elseif(NOT _resolved_commit)
                        set(_candidate_priority 1)
                    endif()
                    if(_candidate_priority GREATER _best_priority)
                        set(_best_priority ${_candidate_priority})
                        set(_resolved_commit "${_candidate_commit}")
                    endif()
                endif()
            endforeach()
            if(_resolved_commit)
                string(SUBSTRING "${_resolved_commit}" 0 7 _resolved_commit)
            endif()
        endif()
    endif()
    set("${output_variable}" "${_resolved_commit}" PARENT_SCOPE)
endfunction()
